version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'bd-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=java-bd'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    links:
      - 'postgres:my-db'
